### get all
GET http://localhost:8080/api/content

### create one
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "second Post",
  "description": "second post",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2024-08-26T16:03:43.8649707",
  "dateUpdated": null,
  "url": ""
}

### update by id
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": "update",
  "description": "update",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2024-08-26T16:03:43.8649707",
  "dateUpdated": null,
  "url": ""
}

### delete by id
DELETE http://localhost:8080/api/content/1



